const ADD_TASK = "ADD_TASK";
const DELETE_TASK = "DELETE_TASK";
const TOGGLE_TASK = "TOGGLE_TASK";
const FETCH_TASKS = "FETCH_TASKS";
const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
const FETCH_TASKS_ERROR = "FETCH_TASKS_ERROR";

export {
  ADD_TASK,
  DELETE_TASK,
  TOGGLE_TASK,
  FETCH_TASKS,
  FETCH_TASKS_SUCCESS,
  FETCH_TASKS_ERROR,
};
